### ISSUE TITLE
Link between chats and attachments

### ISSUE THREAD

**Issue by Mebus** [pajowu/signal-backup-decode#15]
Plase make it possible to extract the attachments to subfolders, that carry the name of the chats, which they belong to.

**Comment by Mebus** [comment]
I have built this:

https://github.com/Mebus/signal-backup-decode-media-mebus

as a workaround. It works, but should be implemented in signal-backup-decode directly.

**Comment by pajowu** [comment]
I feel like this is out of scope. The idea behind this was to create a small tool that extracts the backup without loosing information but nothing more. Since this required reading the database I think this is better handled in another tool
