### ISSUE TITLE
frame with unsupported number of fields

### ISSUE THREAD

**Issue by johnkg77** [pajowu/signal-backup-decode#18]
I cloned the git repo and built the app.  When running, it ran through many frames but then ended with an error.  It wrote a 0 byte db file, but the attachment folder had many correct multimedia files.  Here is the error it gave:

Database Version: 39d 1 frames, 0 attachments, 54 bytes into file
thread 'main' panicked at 'Frame with an unsupported number of fields found, please report to author: ', src/main.rs:184:4
stack backtrace:
   0:     0x55c89a6f5ac1 - std::sys_common::backtrace::print::hc37753fd01765e69
   1:     0x55c89a6fb132 - std::panicking::default_hook::{{closure}}::h827f84ab19d3ba68
   2:     0x55c89a6faec3 - std::panicking::default_hook::h7a61e2fabd403e6d
   3:     0x55c89a6fb7c0 - std::panicking::rust_panic_with_hook::hdf58d8a3e45412d2
   4:     0x55c89a6fb352 - std::panicking::continue_panic_fmt::hf338451f3b80117e
   5:     0x55c89a6fb29f - std::panicking::begin_panic_fmt::h340a50431228f96f
   6:     0x55c89a17eec9 - signal_backup_decode::decode_backup::h9a5a2fccc46de4c9
                               at src/main.rs:184
   7:     0x55c89a149489 - signal_backup_decode::main::h4431f494941a0f5d
                               at src/main.rs:421
   8:     0x55c89a14a832 - std::rt::lang_start::{{closure}}::hac4be1922d26fad6
                               at /usr/src/rustc-1.37.0/src/libstd/rt.rs:64
   9:     0x55c89a6fb1d3 - std::panicking::try::do_call::h78186ff532cc12a3
  10:     0x55c89a6fc78a - __rust_maybe_catch_panic
  11:     0x55c89a6ef919 - std::rt::lang_start_internal::h54a47c0b3c8d65e6
  12:     0x55c89a14a7f9 - std::rt::lang_start::hee63aa837b8b929d
                               at /usr/src/rustc-1.37.0/src/libstd/rt.rs:64
  13:     0x55c89a14a71a - main
  14:     0x7f10591ff1e3 - __libc_start_main
  15:     0x55c89a10535e - _start
  16:                0x0 - <unknown>

Thanks for the help.

**Comment by pajowu** [comment]
I was busy over the holidays and the 36c3 and didn't have time to look at it earlier. This seems related to signal adding stickers. Please try the version in the `stickers` branch, that should have fixed it (at least for me)
