### ISSUE TITLE
thread 'main' panicked at 'Could not parse frame from [215, 203, 183, 214]: WireError(UnexpectedEof)'

### ISSUE THREAD

**Issue by tomheinisch** [pajowu/signal-backup-decode#22]
This is the command I'm running:

`signal-backup-decode --no-verify-mac -p password ./signal-2020-02-25-13-27-53.backup
`
I'm currently running it on the Linux subsystem on Windows 10 (Ubuntu).

The backup file's size is roughly 527MB.

I've attached the output with RUST_BACKTRACE=full to this issue.
[signal-backup-decode_output.txt](https://github.com/pajowu/signal-backup-decode/files/4255977/signal-backup-decode_output.txt)

**Comment by pajowu** [comment]
Were you able to resolve the issue? I cannot really debug much from here. If you can run a debug build and send me the backtrace it might be possible. However I don't think I can really figure it out without the backup file.

**Comment by mutlusun** [comment]
Hello,
[signalbackup-tools](https://github.com/bepaald/signalbackup-tools) offers some options to decrypt/recover corrupted backup files. This seems to be not that uncommon. Maybe your backup file is corrupted as well. Maybe it is possible to add these features to signal-backup-decode as well in the future ...
