### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by sburris0** [pajowu/signal-backup-decode#26]
Hi, I would like to package this for Void Linux. 
Void build templates need a release version specified for fetching source code from Github.
I see that this is versioned in Cargo.toml, @pajowu would you mind creating a release for 0.1.3?

Thank you for making this! It's proven to be very useful.

**Comment by pajowu** [comment]
Hey, i just uploaded version 0.1.5 to crates.io, tagged the commit and created a github release. It that enough? Do you need something else?

**Comment by sburris0** [comment]
Nope, that is all. Thanks.
Here's the PR: https://github.com/void-linux/void-packages/pull/23539

**Comment by sburris0** [comment]
Turns out the builds fail on ARMv8 because rust-crypto is not maintained. #27

**Comment by pajowu** [comment]
I tagged and uploaded a new release, I hope you can finish the package now

**Comment by sburris0** [comment]
@pajowu Sorry, I should have been more specific. Void packages pull source from releases on Github, not cargo.

**Comment by pajowu** [comment]
Done as well
