### ISSUE TITLE
rust-crypto is unmaintained and blocking aarch64 builds

### ISSUE THREAD

**Issue by sburris0** [pajowu/signal-backup-decode#27]
Hi, the void package is mostly finished but build fails on aarch64 and aarch64-musl.
`rust-crypto` is no longer maintained and will not build on ARMv8, https://github.com/RustCrypto is the replacement.

There is also a suggestion to regenerate .rs files from the .proto because `protobuf::lazy::Lazy` is deprecated.
Full log aarch64 build log: https://travis-ci.org/github/void-linux/void-packages/jobs/707474030

**Comment by pajowu** [comment]
This should be fixed with #25 which I plan to merge this week
