### ISSUE TITLE
Ask about install

### ISSUE THREAD

**Issue by TurzyRGD** [pajowu/signal-backup-decode#28]
Hi!
I'm a not programmer but i don't know where could i ask about help.
I have problem with use this code.
I tried almost everything. Could you help me?

I cant install decoder because:

> firenet@firenet-VirtualBox:~/.cargo/registry/src/github.com-1ecc6299db9ec823/signal-backup-decode-0.1.5$ cargo install --features "rebuild-protobuf" signal-backup-decode
Updating crates.io index
Installing signal-backup-decode v0.1.5
Compiling libc v0.2.74
Compiling cfg-if v0.1.10
Compiling getrandom v0.1.14
Compiling proc-macro2 v1.0.19
Compiling cc v1.0.59
Compiling pkg-config v0.3.18
Compiling autocfg v1.0.0
Compiling unicode-xid v0.2.1
Compiling ppv-lite86 v0.2.8
Compiling syn v1.0.38
Compiling log v0.4.11
Compiling protobuf v2.17.0
Compiling bitflags v1.2.1
Compiling remove_dir_all v0.5.3
Compiling gcc v0.3.55
Compiling gimli v0.22.0
Compiling version_check v0.9.2
Compiling ahash v0.3.8
Compiling adler v0.2.3
Compiling foreign-types-shared v0.1.1
Compiling rustc-demangle v0.1.16
Compiling byteorder v1.3.4
Compiling object v0.20.0
Compiling unicode-width v0.1.8
Compiling openssl v0.10.30
Compiling rustc-serialize v0.3.24
Compiling ansi_term v0.11.0
Compiling strsim v0.8.0
Compiling lazy_static v1.4.0
Compiling vec_map v0.8.2
Compiling hex v0.3.2
Compiling sqlite3-src v0.2.12
Compiling hashbrown v0.7.2
Compiling openssl-sys v0.9.58
Compiling rust-crypto v0.2.36
Compiling addr2line v0.13.0
Compiling error-chain v0.12.4
Compiling miniz_oxide v0.4.0
Compiling foreign-types v0.3.2
Compiling textwrap v0.11.0
> error[E0658]: non-builtin inner attributes are unstable
--> /home/firenet/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/descriptor.rs:9:1
|
9 | #![rustfmt::skip]
| ^^^^^^^^^^^^^^^^^
|
= note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information

> error[E0658]: non-builtin inner attributes are unstable
--> /home/firenet/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/plugin.rs:9:1
|
9 | #![rustfmt::skip]
| ^^^^^^^^^^^^^^^^^
|
= note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information

> error[E0658]: non-builtin inner attributes are unstable
--> /home/firenet/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/rustproto.rs:9:1
|
9 | #![rustfmt::skip]
| ^^^^^^^^^^^^^^^^^
|
= note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information

> error[E0658]: non-builtin inner attributes are unstable
--> /home/firenet/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/well_known_types/any.rs:9:1
|
9 | #![rustfmt::skip]
| ^^^^^^^^^^^^^^^^^
|
= note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information

> error[E0658]: non-builtin inner attributes are unstable
--> /home/firenet/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/well_known_types/api.rs:9:1
|
9 | #![rustfmt::skip]
| ^^^^^^^^^^^^^^^^^
|
= note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information

> error[E0658]: non-builtin inner attributes are unstable
--> /home/firenet/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/well_known_types/duration.rs:9:1
|
9 | #![rustfmt::skip]
| ^^^^^^^^^^^^^^^^^
|
= note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information

> error[E0658]: non-builtin inner attributes are unstable
--> /home/firenet/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/well_known_types/empty.rs:9:1
|
9 | #![rustfmt::skip]
| ^^^^^^^^^^^^^^^^^
|
= note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information

> error[E0658]: non-builtin inner attributes are unstable
--> /home/firenet/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/well_known_types/field_mask.rs:9:1
|
9 | #![rustfmt::skip]
| ^^^^^^^^^^^^^^^^^
|
= note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information

> error[E0658]: non-builtin inner attributes are unstable
--> /home/firenet/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/well_known_types/source_context.rs:9:1
|
9 | #![rustfmt::skip]
| ^^^^^^^^^^^^^^^^^
|
= note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information

> error[E0658]: non-builtin inner attributes are unstable
--> /home/firenet/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/well_known_types/struct_pb.rs:9:1
|
9 | #![rustfmt::skip]
| ^^^^^^^^^^^^^^^^^
|
= note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information

> error[E0658]: non-builtin inner attributes are unstable
--> /home/firenet/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/well_known_types/timestamp.rs:9:1
|
9 | #![rustfmt::skip]
| ^^^^^^^^^^^^^^^^^
|
= note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information

> error[E0658]: non-builtin inner attributes are unstable
--> /home/firenet/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/well_known_types/type_pb.rs:9:1
|
9 | #![rustfmt::skip]
| ^^^^^^^^^^^^^^^^^
|
= note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information

> error[E0658]: non-builtin inner attributes are unstable
--> /home/firenet/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.17.0/src/well_known_types/wrappers.rs:9:1
|
9 | #![rustfmt::skip]
| ^^^^^^^^^^^^^^^^^
|
= note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information

> error: aborting due to 13 previous errors

> For more information about this error, try `rustc --explain E0658`.
> error: failed to compile `signal-backup-decode v0.1.5`, intermediate artifacts can be found at `/tmp/cargo-installvZAI7X`

> Caused by:
> could not compile `protobuf`.

> To learn more, run the command again with --verbose.

**Comment by mutlusun** [comment]
Hello,
are you on the latest rust version? Maybe it will help to fix this issue.
What is the output of `rustc -V`

Best

**Comment by TurzyRGD** [comment]
I don't know how, but install is complete, but now I have a new problem:

> Successfully exported 3747 frames, 267 attachments, 186008306 bytes into f
Successfully exported 3748 frames, 267 attachments, 186009173 bytes into f
Successfully exported 3749 frames, 268 attachments, 186921020 bytes into f
Successfully exported 3750 frames, 268 attachments, 186921887 bytes into f
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(MacVerificationError([227, 153, 138, 118, 97, 241, 107, 128, 224, 104], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', /home/firenet/.cargo/registry/src/github.com-1ecc6299db9ec823/signal-backup-decode-0.1.5/src/main.rs:448:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

after use 
> signal-backup-decode /home/firenet/Pobrane/signal-2020-08-11-14-14-26.backup --sqlite-path /home/firenet/Pobrane/Database/ -p xxxxxxxxxxxxxxxxxx

command it's ok?

**Comment by mutlusun** [comment]
This is a HMAC verification error. Is your backup file corrupted? This happens sometimes. Maybe you can try to run signal-backup-decode with the following argument: `--no-verify-mac`.

Does this help?

**Comment by TurzyRGD** [comment]
At 100% is not corrupted, because i extracterd media from this program: [https://github.com/xeals/signal-back](url). From this program working too, but not messages :( .

MacVeryficationError disappeared, but stay error yet:

> thread` 'main' panicked at 'index 18446744073709551606 out of range for slice of length 0', /home/firenet/.cargo/registry/src/github.com-1ecc6299db9ec823/signal-backup-decode-0.1.5/src/main.rs:45:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by mutlusun** [comment]
If your backup file is corrupt, it will be hard to debug problems without the file. However, you might have a look at https://github.com/bepaald/signalbackup-tools. This project offers some possibilities to obtain intact messages and files.

**Comment by TurzyRGD** [comment]
It's your right. This backup was corrupted. I maked, a new one and that working! Thank you for help :)
Maybe you have signatures of tabels and columns yet? ;)
