### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by chrstn-hntschl** [pajowu/signal-backup-decode#32]
The provided `cargo install signal-backup-decode` fails with

```
error[E0658]: non-builtin inner attributes are unstable
 --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.18.0/src/descriptor.rs:9:1
  |
9 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/54726
```
I assume this error is not in signal-backup-decode, but maybe the protobuf dependency needs to be updated? I am trying to build under debian stretch.

**Comment by pajowu** [comment]
What version of rust are you using (Output of `rustc --version`)

**Comment by pajowu** [comment]
I downgraded the protobuf version, currently checking that everything works. If it does I will upload a new version to crates and post here again

**Comment by pajowu** [comment]
Version `0.2.1` is now uploaded to crates.io

**Comment by chrstn-hntschl** [comment]
Thanks - does work now!
Here is a Dockerfile to build with all necessary depenencies:

```
FROM rust:1.42.0-slim-stretch

# Ignore APT warnings about not having a TTY
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -qq -y --no-install-recommends \
    libssl-dev pkg-config libsqlite3-dev

RUN cargo install signal-backup-decode

ENTRYPOINT ["signal-backup-decode"]
CMD ["--help"]
```

**Comment by pajowu** [comment]
Oh nice. If you want you can open a Pull Request to add that dockerfile. I'd be happy to merge that
