### ISSUE TITLE
DB Version 90: Frame with an unsupported number of fields found, please report to author

### ISSUE THREAD

**Issue by psy** [pajowu/signal-backup-decode#39]
Ohai,

since Database Version 90 (seems like it was introduced a few days ago) I'm getting the following error while decoding backups:
```
thread '<unnamed>' panicked at 'Frame with an unsupported number of fields found, please report to author: '
```

Could you take a look at this please? Thanks for providing the tool, I really enjoy using it! :)

**Comment by pajowu** [comment]
I just pushed a new commit that *should* fix that. Once the CI runs I will tag a new version to crates.io

**Comment by pajowu** [comment]
New version is tagged and uploaded to crates.io. Please note that the new database version is not yet fully supported (see #40)
