### ISSUE TITLE
Process getting locked but I don't know why or how.

### ISSUE THREAD

**Issue by DaveKap** [pajowu/signal-backup-decode#4]
Windows 7. After running the command, it seems like the program runs for a while but then ends with this error. I see no good reason for this error to happen, I'm definitely not trying to access these files through any other program. Tried it again without anti-virus, in case that was the cause, but that wasn't it either. Any clues for what might be locking the process?

```
X:\asdf>signal-backup-decode --sqlite-path X:\sqlite  signal-2018-05-26-16-44-13
.backup --password <removed for security purposes>
Database Version: 7ed 1 frames, 0 attachments, 54 bytes into file
The process cannot access the file because it is being used by another process.
(os error 32), Could not move C:\Users\DAVEKA~1\AppData\Local\Temp\.tmpxGtzSp\si
gnal_backup.sqlite to X:\sqlite, trying copy
Error: Error(Io(Os { code: 32, kind: Other, message: "The process cannot access
the file because it is being used by another process." }), State { next_error: N
one, backtrace: None })
```

**Comment by pajowu** [comment]
hey, could you try to run the tool with `--no-tmp-sqlite`? With that the tool will be much slower, but it should fix this issue. Also the sqlite file should be available in `X:\sqlite`. The error seems to occur when this tool tries to remove the temporary file. If not check the temporary file itself (`C:\Users\DAVEKA~1\AppData\Local\Temp\.tmpxGtzSp\signal_backup.sqlite` in this case)

**Comment by DaveKap** [comment]
I think that worked but I'm honestly not sure. I'm trying to use this to merge my signal history into my normal default android SMS/MMS history but the output of running the script sent nothing to X:\sqlite but it did create 3 folders which don't seem to be formatted in a data set that I understand how to use.

Was I perhaps expecting too much out of this repo?

**Comment by pajowu** [comment]
The files in the `avatars` folder are JPGs, the files in the `config` folder are plaintext files, the files in the `attachments` folder are different file types. They can be anything from JPGs to PDFs to ZIPs, depending on what you send. To identifiy the file types, you might want to use somthing like `file` on linux or [`TrID`](http://mark0.net/soft-tridnet-e.html) on windows

**Comment by DaveKap** [comment]
Going to make a new issue with a wiki edit suggestion.
