### ISSUE TITLE
New release on github for 0.2.3

### ISSUE THREAD

**Issue by quintrino** [pajowu/signal-backup-decode#46]
Hi, 

It looks like the latest `release` visible on github is 0.2.1 but 0.2.3 according to `tags`. 
<img width="347" alt="image" src="https://user-images.githubusercontent.com/7043587/116642963-54178600-a9b3-11eb-92c0-10e3a6386f02.png">

Are you able to update github with a new release?

**Comment by pajowu** [comment]
Done!
